name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # consistent with go.mod
      - name: Vet Go files
        run: go vet ./...
      - name: Ensure go.mod and go.sum are tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum
      - name: Install dependencies
        run: |
          go install github.com/gogo/protobuf/protoc-gen-gogofaster@v1.3.2
      - name: Ensure all Go generated files are up to date
        run: |
          go generate ./...
          git diff --exit-code
      - name: Ensure all Proto files are up to date
        run: |
          make proto-all
          git diff --exit-code
